### ISSUE TITLE
Добавить поддержку OpenTelementy

### ISSUE THREAD

**Issue by govorovvs** [Byndyusoft/Byndyusoft.Logging#10]
Нужно реализовать добавление в логи TraceId и SpanId из Activity.Current. 
Предлагается реализовать это в отдельном пакете

**Comment by govorovvs** [comment]
https://github.com/RehanSaeed/Serilog.Enrichers.Span

**Comment by kanybekov** [comment]
Энричеры вынести в отдельный пакет
Экстеншены вынести в отдельный пакет

**Comment by litichevskiydv** [comment]
+ Добавим в Readme, что логирование идет через Serilog

**Comment by litichevskiydv** [comment]
Пока в процессе, Рома распилил пакет на части , сейчас нужно подправить доку и опубликовать, ждем итоговую версию 13.07

**Comment by litichevskiydv** [comment]
На следующей неделе (с 01.08 ) сливаем PR, поскольку он прошел ревью,  добавляем поддержку OpenTelemtry в шаблон, и уже после этого переводим его на net6

**Comment by KillWolfVlad** [comment]
Рома сделал. Ринан заюзал в шаблоне.
